### ISSUE TITLE
Haar

### ISSUE THREAD

**Issue by mariohmol** [hasaan21/Car-Number-Plate-Recognition-Sysytem#1]
Hi,

first of all, thats is awesome!!

Could you share how to create haar files for other plates patterns?

Examples:
* http://www.diretonegocios.com.br/blog/wp-content/uploads/2014/12/Placa_carro_antiga.jpg
* https://www.comparaonline.com.br/blog-statics/br/uploads/2014/11/Placa-Brasil.png

Thanks a lot!

**Comment by hasaan21** [comment]
Hi,

Thank you for the compliment!

I believe you can use same haar cascade, that I have used but, If you want to train your own custom haar cascade, please go through this blog.

https://link.medium.com/c50dE5Nibkb

I found this blog amazingly helpful.

**Comment by mariohmol** [comment]
Hi thanks a lot!!!
